Puzzle15/Models/Pictures.cs
using System;
using System.Collections.Generic;

namespace Puzzle15.Models
{
    public partial class Pictures
    {
        public int PicId { get; set; }
        public string PicName { get; set; }
    }
}

Puzzle15/Models/Puzzle15Context.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Puzzle15.Models
{
    public partial class Puzzle15Context : DbContext
    {
        public Puzzle15Context()
        {
        }

        public Puzzle15Context(DbContextOptions<Puzzle15Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Pictures> Pictures { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Server=JASONPC;Database=Puzzle15;Trusted_Connection=True;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Pictures>(entity =>
            {
                entity.HasKey(e => e.PicId)
                    .HasName("PK__pictures__06707FCDD130065D");

                entity.ToTable("pictures");

                entity.Property(e => e.PicId).HasColumnName("picID");

                entity.Property(e => e.PicName)
                    .HasColumnName("picName")
                    .HasMaxLength(255)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Puzzle15/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Puzzle15.Models;

namespace Puzzle15.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

Puzzle15/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Puzzle15.Models;

namespace Puzzle15.Controllers
{
    public class PicturesController : Controller
    {
        private readonly Puzzle15Context _context;

        public PicturesController(Puzzle15Context context)
        {
            _context = context;
        }

        // GET: Pictures
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pictures.ToListAsync());
        }

        // GET: Pictures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pictures = await _context.Pictures
                .FirstOrDefaultAsync(m => m.PicId == id);
            if (pictures == null)
            {
                return NotFound();
            }

            return View(pictures);
        }

        // GET: Pictures/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pictures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PicId,PicName")] Pictures pictures)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pictures);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pictures);
        }

        // GET: Pictures/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pictures = await _context.Pictures.FindAsync(id);
            if (pictures == null)
            {
                return NotFound();
            }
            return View(pictures);
        }

        // POST: Pictures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PicId,PicName")] Pictures pictures)
        {
            if (id != pictures.PicId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pictures);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PicturesExists(pictures.PicId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pictures);
        }

        // GET: Pictures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pictures = await _context.Pictures
                .FirstOrDefaultAsync(m => m.PicId == id);
            if (pictures == null)
            {
                return NotFound();
            }

            return View(pictures);
        }

        // POST: Pictures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pictures = await _context.Pictures.FindAsync(id);
            _context.Pictures.Remove(pictures);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PicturesExists(int id)
        {
            return _context.Pictures.Any(e => e.PicId == id);
        }
    }
}

Puzzle15/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="row">
    <div class="col-sm-12 col-md-3">
        <div class="card text-center">
            <img src="/images/1.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <a href="#" class="btn btn-primary">Show/Hide image</a>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-6 puzzle-col">
        <div class="card text-center">
            <div class="card-body">
                <h2 class="card-title">Super Puzzle Slider Turbo</h2>
                <p class="card-text">A classic sliding piece puzzle game.</p>
                <a href="#" class="btn btn-primary">Start Sliding!</a>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-3 col-use-this">
        <div class="card text-center">
            <img src="/images/2.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <div class="row align-items-center">
                    <i class="fa fa-caret-left fa-3x" aria-hidden="true"></i>
                    <a href="#" class="btn btn-primary">Use this image</a>
                    <i class="fa fa-caret-right fa-3x" aria-hidden="true"></i>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-3 side-col">
            <a href="#" class="btn btn-primary btn-block">EASY</a>
            <a href="#" class="btn btn-primary btn-block">MEDIUM</a>
            <a href="#" class="btn btn-primary btn-block">HARD</a>
        </div>
        <div class="col-sm-12 col-md-6">
            <!--<img src="/images/2.jpg" class="img-fluid" />-->
            <p><button class="btn btn-primary btn-lg" onclick="restart()">Start!</button></p>
            <div id="overall">
                <div id="puzzlearea">
                    <!-- the following are the fifteen puzzle pieces -->
                    <div>1</div>  <div>2</div>  <div>3</div>  <div>4</div>
                    <div>5</div>  <div>6</div>  <div>7</div>  <div>8</div>
                    <div>9</div>  <div>10</div> <div>11</div> <div>12</div>
                    <div>13</div> <div>14</div> <div>15</div>
                </div>

                <div id="controls">
                    <button id="shufflebutton">Shuffle</button>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-3 side-col">
            <a href="#" class="btn btn-primary btn-block">COLOR</a>
            <a href="#" class="btn btn-primary btn-block">B&W</a>
            <a href="#" class="btn btn-primary btn-block">LINE</a>
        </div>
    </div>
</div>
            <!--
            <h1 class="display-4 text-center">Super Puzzle Slider Turbo</h1>
            <button class="btn btn-primary btn-lg">Start!</button>
            <div class="container">
                <div class="row">
                    <div class="col">
                        <a asp-action="Index" asp-controller="Pictures" class="btn btn-primary">Pictures</a>
                    </div>
                </div>
            </div>-->
                    <!--
            <p><button class="btn btn-primary btn-lg" onclick="restart()">Start!</button></p>
            <div id="overall">
                <div id="puzzlearea">
                    <!-- the following are the fifteen puzzle pieces --
                    <div>1</div>  <div>2</div>  <div>3</div>  <div>4</div>
                    <div>5</div>  <div>6</div>  <div>7</div>  <div>8</div>
                    <div>9</div>  <div>10</div> <div>11</div> <div>12</div>
                    <div>13</div> <div>14</div> <div>15</div>
                </div>

                <div id="controls">
                    <button id="shufflebutton">Shuffle</button>
                </div>
            </div>-->

Puzzle15/Views/Pictures/Create.cshtml
@model Puzzle15.Models.Pictures

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pictures</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PicName" class="control-label"></label>
                <input asp-for="PicName" class="form-control" />
                <span asp-validation-for="PicName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Puzzle15/Views/Pictures/Delete.cshtml
@model Puzzle15.Models.Pictures

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pictures</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PicName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PicName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PicId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Puzzle15/Views/Pictures/Details.cshtml
@model Puzzle15.Models.Pictures

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pictures</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PicName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PicName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PicId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Puzzle15/Views/Pictures/Edit.cshtml
@model Puzzle15.Models.Pictures

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pictures</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PicId" />
            <div class="form-group">
                <label asp-for="PicName" class="control-label"></label>
                <input asp-for="PicName" class="form-control" />
                <span asp-validation-for="PicName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Puzzle15/Views/Pictures/Index.cshtml
@model IEnumerable<Puzzle15.Models.Pictures>

@{
    ViewData["Title"] = "Puzzle 15";
}

<h1>Puzzle Slider Pictures</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PicName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PicName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PicId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PicId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PicId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<a asp-action="Index" asp-controller="Home" class="btn btn-primary">Back to the Game</a>

Puzzle15/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Puzzle15</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/PuzzleStyle.css" />
    <link rel="stylesheet" href="~/css/puzzleExtra.css" />
    <!--<style>
        html, body {
            padding: 0;
            margin: 0;
            padding-top: 8vh;
            //background: #222;
            color: #111
        }

        .txt {
            color: #000;
            text-align: center;
            font-size: 5vh
        }

        .board {
            padding: 0;
            margin: auto;
            width: 33vh;
            height: 33vh
        }

        .button, .empty {
            border: 0;
            font-size: 3.5vh;
            //margin: 0.5vh;
            padding: 0;
            height: 25%;
            //width: 7.25vh;
            width: 25%;
            line-height: 5vh;
            vertical-align: middle;
            background: lightblue;
            text-align: center;
            //border-radius: 3px;
            cursor: pointer;
            float: left
        }

        .empty {
            background: #333;
            border: 1px solid #111
        }
    </style>-->
</head>
<body onload="">   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Puzzle15.js"></script>
    <script src="~/js/canvasjs.min.js"></script>
    <script src="~/js/NewPuzzle.js" ></script>
    @RenderSection("Scripts", required: false)
</body>
</html>